config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path, notice: 'La receta fue eliminada'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recetario</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/create.html.erb
<h1>Recipes#create</h1>
<p>Find me in app/views/recipes/create.html.erb</p>

app/views/recipes/destroy.html.erb
<h1>Recipes#destroy</h1>
<p>Find me in app/views/recipes/destroy.html.erb</p>

app/views/recipes/edit.html.erb
<h1>Recipes#edit</h1>
<p>Find me in app/views/recipes/edit.html.erb</p>

app/views/recipes/index.html.erb
<h1>Recetas</h1>

<ul>
  <% @recipes.each do |recipe| %>
    <li><%= link_to recipe.name, recipe_path(recipe) %></li>
  <% end %>
</ul>

app/views/recipes/new.html.erb
<h1>Recipes#new</h1>
<p>Find me in app/views/recipes/new.html.erb</p>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<h2>Ingredientes:</h2>
<ul>
  <% @recipe.ingredients.each do |ingredient| %>
    <li><%= ingredient.name %>: <%= ingredient.quantity %></li>
  <% end %>
</ul>

<hr>
  <%= link_to "Editar", edit_recipe_path(@recipe), class: "btn btn-primary" %>
  <%= link_to "Regresar", recipes_path, class: "btn btn-secondary" %>
  <%= link_to "Eliminar", recipe_path(@recipe), method: :delete, data: { confirm: '¿Estás seguro de que deseas eliminar esta receta?' }, class: "btn btn-danger" %>

app/views/recipes/update.html.erb
<h1>Recipes#update</h1>
<p>Find me in app/views/recipes/update.html.erb</p>